name: Run Python Script

- name: Install Chrome
  run: |
    sudo apt update
    sudo apt install -y google-chrome-stable

- name: Install ChromeDriver
  run: |
    CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
    sudo apt install -y chromedriver

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"  # Uruchamianie co godzinę

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python script.py
